#!/usr/bin/perl

$branch = (shift or 'master');
`rm -r imageQueue`;
`rm imagedata.fifo`;
`git pull origin $branch`;
`mkdir imageQueue`;
`cp images/0off.png imageQueue/currentImage.png`;
`mkfifo imageData.fifo`;
`chmod 0777 imageQueue`;
